import AbstractVideo from '../abstract-video';
import Rect from '../../geometry/rect';
import IViewPort from '../interfaces/i-view-port';
import HTML5ViewPort from '../../device/common/HTML5-view-port';

export default class HTML5Video extends AbstractVideo {
  protected _viewport: HTML5ViewPort;
  protected _container: HTMLDivElement;
  protected _video: HTMLVideoElement;
  protected _source: HTMLElement;
  protected _startTime: number;
  constructor(rect: Rect);
  public play(url: string, opt_startFrom?: number);
  public resume(): void;
  public pause(): void;
  public stop(): void;
  public forward(): boolean;
  public rewind(): boolean;
  public destroy(): void;
  public setPlaybackRate(rate: number): void;
  public getPlaybackRate(): number;
  public setPosition(milliseconds: number): void;
  public getPosition(): number;
  public getDuration(): number;
  public setVolume(value: number): void;
  public getVolume(): number;
  public getUrl(): string;
  public setMuted(value: boolean): void;
  public getMuted(): boolean;
  protected _createViewPort(containerRect: Rect): IViewPort;
  protected _createVideoObject(): HTMLVideoElement;
  protected _createContainer(): HTMLDivElement;
  protected _initVideoObject(url: string): void;
  protected _errorEventListener(event: ErrorEvent): void;
  protected _loadedmetadataEventListener(): void;
  protected _playingEventListener(): void;
  protected _durationchangeEventListener(): void;
  protected _timeupdateEventListener(): void;
  protected _pauseEventListener(): void;
  protected _ratechangeEventListener(): void;
  protected _volumechangeEventListener(): void;
  protected _loadstartEventListener(): void;
  protected _endedEventListener(): void;
  protected _waitingEventListener(): void;
  protected _initEvents(): void;
  protected _destroyEvents(): void;
  protected _removeVideoObject(): void;
  protected _removeContainer(): void;
  protected _fireError(error: string): void;
  protected _seekByPlaybackRateDoubling(): boolean;
}
